on:
  pull_request:

name: Run Tests
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and Test
        run: mvn test

      - name: Extract elapsed time
        run: |
          cat target/surefire-reports/dev.moyis.parallelism.FernetServiceTest.txt 
          | grep "Time elapsed:"
          | sed -n 's/.*Time elapsed: \([0-9.]*\) s.*/\1/p'