on:
  pull_request:

name: Run Tests
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and Test
        run: mvn test

      - id: elapsed-time
        name: Extract elapsed time
        run: |
          cat target/surefire-reports/dev.moyis.parallelism.FernetServiceTest.txt |
          grep "Time elapsed:" |
          sed -n 's/.*Time elapsed: \([0-9.]*\) s.*/\1/p' |
          { read time; echo "TIME=$time"; } >> $GITHUB_OUTPUT

      - name: Install redis
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Write to Redis
        env:
          REDIS_URL: ${{ secrets.REDIS_CONNECTION_STRING }}
          TIME: ${{ steps.elapsed-time.outputs.TIME }}
        run: |
          echo "Writing test time $TIME to Redis"
          redis-cli --tls -u "$REDIS_URL" ZADD parallelism "$TIME" "${{ github.event.pull_request.user.id }}-${{ github.event.pull_request.user.login }}"